### ISSUE TITLE
Compilation error in chapter_15 after recent commit

### ISSUE THREAD

**Issue by kamidev** [Cinderella-Man/hands-on-elixir-and-otp-cryptocurrency-trading-bot-source-code#5]
== Compilation error in file lib/binance_mock.ex ==
** (CompileError) lib/binance_mock.ex:275: undefined function symbol/0

A recent commit removed the local variable "symbol". 
I changed "symbol" to "trade_event.symbol" to fix this.

Thanks a lot for your book and the great sample code!

**Comment by Cinderella-Man** [comment]
Hi :wave: 

I'm really sorry for that - I was trying to simplify things (by updating the book/code to all uppercase topic names) and ended up breaking them :disappointed:  Thank you very much for pointing out this issue :clap: 

I updated 12 branches with the bugfix and released a new version of the book! :+1: 

> Thanks a lot for your book and the great sample code!

I hope it will get even better with time because of great contributors like :wink:

**Comment by kamidev** [comment]
Great! No need to apologize, this was basically a typo. I had a really good time running through your book chapter by chapter a few days ago. Working code and clean commits after each chapter made it easy to keep going and test things without getting stuck.
